#!/bin/bash

read -p "What is your first name?: " name
echo
read -N 3 -p "What is your extension number?(enter only 3 characters): " ext
echo
read -N 4 -s -p"What access code would you like to use when dialing in?: " pin

echo "$name,$ext,$pin" >> extensions.csv